language: android
sudo: required
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.1
  - android-22
  - android-26
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_script:
  - chmod +x gradlew
script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck
